site_name: MathWallet API Documentation
site_description: In Math We Trust!
site_author: MathWallet


site_url: http://doc.mathwallet.org/
repo_url: https://github.com/mathwallet/doc.mathwallet.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathWallet

pages:
    - Home: index.md
    - English:
        - BTC: en/btc.md
        - ETH: en/eth.md
        - Polkadot: en/polkadot.md
        - BSC: en/bsc.md
        - Solana: en/solana.md
        - Filecoin: en/filecoin.md
        - TRON: en/tron.md
        - Cosmos: en/cosmos.md
        - BinanceChain: en/binance.md
        - Near: en/near.md
        - EOS: en/eos.md
        - Terra: en/terra.md
        - Nervos: en/nervos.md
        - Conflux: en/conflux.md
        - PlatON: en/platon.md
        - More: en/more.md
    - 中文:
        - BTC: cn/btc.md
        - ETH: cn/eth.md
        - Polkadot: cn/polkadot.md
        - BSC: cn/bsc.md
        - Solana: cn/solana.md
        - Filecoin: cn/filecoin.md
        - TRON: cn/tron.md
        - Cosmos: cn/cosmos.md
        - BinanceChain: cn/binance.md
        - Near: cn/near.md
        - EOS: cn/eos.md
        - Terra: cn/terra.md
        - Nervos: cn/nervos.md
        - Conflux: cn/conflux.md
        - PlatON: cn/platon.md
        - 更多问题: cn/more.md

plugins:
    - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/mathwallet'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/mathwallet'
