site_name: MathWallet API Documentation
site_description: In Math We Trust!
site_author: MathWallet


site_url: http://doc.mathwallet.org/
repo_url: https://github.com/mathwallet/doc.mathwallet.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathWallet

pages:
    - Home: index.md
    - 中文:
        - EOS: cn/eos.md
        - ETH: cn/eth.md
        - Polkadot: cn/polkadot.md
        - TRON: cn/tron.md
        - Binance: cn/binance.md
        - Cosmos: cn/cosmos.md
        - IRISnet: cn/iris.md
        - ONT: cn/ont.md
        - ChainX: cn/chainx.md
        - BTC: cn/btc.md
        - NEO: cn/neo.md
        - EOS原力: cn/eosforce.md
        - CODEX: cn/codex.md
        - BOS: cn/bos.md
        - Telos: cn/telos.md
        - ENU: cn/enu.md
        - 更多问题: cn/more.md
    - English:
        - EOS: en/eos.md
        - ETH: en/eth.md
        - Polkadot: en/polkadot.md
        - TRON: en/tron.md
        - Binance: en/binance.md
        - Cosmos: en/cosmos.md
        - IRISnet: en/iris.md
        - ONT: en/ont.md
        - ChainX: en/chainx.md
        - BTC: en/btc.md
        - NEO: en/neo.md
        - EOSForce: en/eosforce.md
        - CODEX: en/codex.md
        - BOS: en/bos.md
        - Telos: en/telos.md
        - ENU: en/enu.md
        - More: en/more.md

plugins:
    - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/mathwallet'
    - type: 'twitter'
      link: 'https://twitter.com/mathwallet'