site_name: MediShares Help
site_description: The World's First Mutual Aid Marketplace On BlockChain
site_author: MediShares


site_url: http://help.medishares.org/
repo_url: https://github.com/MediShares/mds-help

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MediShares

pages:
    - Home: index.md
    - 中文:
        - 常见问题: cn/QA.md
        - 如何导入钱包到麦子钱包: cn/importwallet.md
        - 如何设置修改钱包名称: cn/renamewallet.md
        - 如何从交易所提现到麦子钱包: cn/withdraw2wallet.md
    - English:
        - QA: en/QA.md

plugins:
    - search